---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tdarr

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-tdarr
commonLabels:
  app: tdarr

resources:
- resources/deployments.yaml
- resources/ingresses.yaml
- resources/namespaces.yaml
- resources/pvcs.yaml
- resources/services.yaml
patches:
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: tdarr
      namespace: tdarr
      annotations:
        gethomepage.dev/href: https://tdarr.crt.house
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Media Transcoder
        gethomepage.dev/group: Media
        gethomepage.dev/icon: tdarr
        gethomepage.dev/name: Tdarr
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
