---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdarr-server
  namespace: tdarr
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tdarr-server
  template:
    metadata:
      labels:
        app: tdarr-server
    spec:
      containers:
        - name: tdarr
          image: tdarr-server
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/Detroit
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: internalNode
              value: "false"
            - name: inContainer
              value: "true"
            - name: ffmpegVersion
              value: "7"
            - name: auth
              value: "false"
            - name: openBrowser
              value: "false"
            - name: maxLogSizeMB
              value: "10"
            - name: cronPluginUpdate
              value: ""
            - name: serverIP
              value: "0.0.0.0"
            - name: serverPort
              value: "8266"
            - name: webUIPort
              value: "8265"
          ports:
            - name: http
              containerPort: 8265
              protocol: TCP
            - name: tdarr-server
              containerPort: 8266
              protocol: TCP
          volumeMounts:
            - mountPath: /app/server
              name: server
            - mountPath: /app/configs
              name: configs
            - mountPath: /media
              name: media
          resources:
            limits:
              memory: 4Gi
      volumes:
      - name: server
        persistentVolumeClaim:
          claimName: tdarr
      - name: configs
        persistentVolumeClaim:
          claimName: tdarr-configs
      - name: media
        nfs:
          path: /volume1/media
          server: 192.168.1.21
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdarr-node
  namespace: tdarr
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tdarr-node
  template:
    metadata:
      labels:
        app: tdarr-node
    spec:
      containers:
        - name: tdarr
          image: tdarr-node
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/Detroit
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: serverURL
              value: tdarr-server.tdarr.svc.cluster.local
            - name: transcodegpuWorkers
              value: "1"
            - name: transcodecpuWorkers
              value: "0"
            - name: healthcheckgpuWorkers
              value: "1"
            - name: healthcheckcpuWorkers
              value: "0"
            - name: inContainer
              value: "true"
            - name: ffmpegVersion
              value: "7"
            - name: maxLogSizeMB
              value: "10"
            - name: cronPluginUpdate
              value: ""
          volumeMounts:
            - mountPath: /media
              name: media
          resources:
            requests:
              gpu.intel.com/i915: "1"
            limits:
              gpu.intel.com/i915: "1"
      volumes:
      - name: media
        nfs:
          path: /volume1/media
          server: 192.168.1.21

