---
apiVersion: v1
kind: Service
metadata:
  name: tdarr
  namespace: tdarr
spec:
  type: ClusterIP
  ports:
  - port: 8265
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: tdarr
---
apiVersion: v1
kind: Service
metadata:
  name: tdarr-server
  namespace: tdarr
spec:
  type: ClusterIP
  ports:
  - port: 8266
    targetPort: tdarr-server
    protocol: TCP
    name: tdarr-server
  selector:
    app: tdarr
